---

- name: copy makepkg.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/makepkg.conf"
    dest: /etc/makepkg.conf

- name: copy ansible_user_id
  ansible.builtin.set_fact:
    local_user: "{{ ansible_user_id }}"

- name: ensure aur build directory
  become: true
  ansible.builtin.file:
    dest: "{{ build_dir }}"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
